# Generated by Django 2.2.5 on 2021-09-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('blog', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=15)),
            ],
        ),
    ]
